variables:
  ANDROID_IMAGE: $ANDROID_DOCKER_IMAGE_URL_JDK_17
  DEFAULT_BRANCH: "main"

stages:
  - automation
  - build
  - test
  - release

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/*

test:
  stage: test
  image: $ANDROID_IMAGE
  script:
    - ./gradlew testDebugUnitTest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: $CI_COMMIT_BRANCH == $DEFAULT_BRANCH
      when: always
    - when: never
  tags:
    - docker


build:
  stage: build
  image: $ANDROID_IMAGE
  script:
    - ./gradlew assemble
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: $CI_COMMIT_BRANCH == $DEFAULT_BRANCH
      when: always
    - when: never
  tags:
    - docker

.automation:
  stage: automation
  image: $ANDROID_IMAGE
  before_script:
    - echo "$TOOLS_PROPERTIES" > tools.properties
    - echo "$TOOLS_SLACK_PROPERTIES" > slack.properties
    - echo "$TOOLS_CONFLUENCE_PROPERTIES" > confluence.properties
    - wget -O tools.jar $TOOLS_JAR_URL
  tags:
    - docker

assign MR:
  extends: .automation
  script:
    - java -jar tools.jar assignMR -mr="$CI_MERGE_REQUEST_IID"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - when: never
  allow_failure: true

check approvals:
  extends: .automation
  script:
    - java -jar tools.jar checkApprovals
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "checkApprovals"'

release minor:
  extends: .automation
  script:
    - java -jar tools.jar makeReleaseBranch
    - java -jar tools.jar buildRelease
    - java -jar tools.jar postReleaseMerges
  rules:
    - if: $CI_COMMIT_BRANCH == $DEFAULT_BRANCH
      when: manual
    - when: never

release patch:
  extends: .automation
  script:
    - java -jar tools.jar makeHotfixBranch
    - java -jar tools.jar buildRelease
    - java -jar tools.jar postReleaseMerges
  rules:
    - if: $CI_COMMIT_BRANCH == $DEFAULT_BRANCH
      when: manual
    - when: never

.release:
  stage: release
  image: $ANDROID_IMAGE
  rules:
    - if: $CI_COMMIT_TAG =~ /^Release\/v[0-9]+\.[0-9]+\.[0-9]+$/
      when: always
    - when: never
  allow_failure: true
  tags:
    - docker

Release to Maven:
  extends: .release
  script:
    - ./gradlew assembleRelease
    - ./gradlew library:publishReleasePublicationToMavenRepository
