name: Release

on:
  push:
    tags:
      - 'Release/*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    name: Publish Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21
      - name: "Set Release Version Env"
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Publish library
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
